// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYqlTbUQbEuw6JX9j248XDrUIaDWnMfB0',
    appId: '1:691250037191:android:9ea1d1eeb3a1afdd8fd9e2',
    messagingSenderId: '691250037191',
    projectId: 'auth-firebase-faa64',
    storageBucket: 'auth-firebase-faa64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4BpkJArPjigGB7wRiGVQvGv0-8mNIKG4',
    appId: '1:691250037191:ios:a4e83056089f74d68fd9e2',
    messagingSenderId: '691250037191',
    projectId: 'auth-firebase-faa64',
    storageBucket: 'auth-firebase-faa64.firebasestorage.app',
    androidClientId: '691250037191-vmqrf85oqm5g8jt0nu77g7j99emjqioj.apps.googleusercontent.com',
    iosClientId: '691250037191-m88oitlinf4rr66tv9cnutcuv13cf15l.apps.googleusercontent.com',
    iosBundleId: 'com.example.jewelleryOrderingApp',
  );

}